version: '3'

volumes:
  dados:

networks:
  banco:
  web:
  fila:

services:

  db:
    image: postgres:10
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts-db:/scripts
      - ./scripts-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco

  frontend:
    image: nginx:1.19
    volumes:
      # Site
      - ./web:/usr/share/nginx/html
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app

  app:
    image: python:3.6
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    # command: bash -c "chmod +x ./app.sh && ./app.sh"
    command: bash ./app.sh
    # ports:
    #   - 8080:8080
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:
      - DB_NAME=abc_sender

  queue:
    image: redis:6.0
    networks:
      - fila

  worker:
    # image: python:3.6
    build: worker
    volumes:
      # Worker
      - ./worker:/worker
    working_dir: /worker
    # command: bash ./app.sh
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
